{% set name = "coq" %}
{% set version = "8.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coq/coq/archive/V{{ version }}.tar.gz
  sha256: 87251327e8a1e25c6b08b5c0ae8e7cdf3a91a5f30832bbe74ccc4f0bde9618ea

build:
  number: 1
  skip: True  # [win]
  detect_binary_files_with_prefix: False
  binary_relocation: False  # [osx]

requirements:
  host:
    - ocaml
    - ocaml-findlib
    - ocaml-num
    - ocaml-camlp5
  run:
    - ocaml
    - ocaml-findlib
    - ocaml-num
    - ocaml-camlp5

test:
  source_files:
    - toplevel/g_toplevel.mlg
  commands:
    - coqc -v
    - coqpp toplevel/g_toplevel.mlg

about:
  home: https://coq.inria.fr
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: 'Coq is a formal proof management system'
  doc_url: https://coq.inria.fr/documentation
  dev_url: https://github.com/coq/coq

extra:
  recipe-maintainers:
    - isuruf
    - slel
