{% set name = "coq" %}
{% set version = "8.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coq/coq/archive/V{{ version }}.tar.gz
  sha256: eea101eff5217dba6d11a8eb13033ed62acb4ee8a64d5cb15fd142e7fc5dc248

build:
  number: 1
  skip: True  # [win]
  detect_binary_files_with_prefix: False
  binary_relocation: False  # [osx]

requirements:
  host:
    - ocaml
    - ocaml-findlib
    - ocaml-num
  run:
    - ocaml
    - ocaml-findlib
    - ocaml-num

test:
  source_files:
    - toplevel/g_toplevel.mlg
  commands:
    - coqc -v
    - coqpp toplevel/g_toplevel.mlg

about:
  home: https://coq.inria.fr
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: 'Coq is a formal proof management system'
  doc_url: https://coq.inria.fr/documentation
  dev_url: https://github.com/coq/coq

extra:
  recipe-maintainers:
    - isuruf
    - slel
