{% set name = "coq" %}
{% set version = "8.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coq/coq/archive/V{{ version }}.tar.gz
  sha256: ecde14c6132f5abb459e7f4724788788928174ad4484fff88e86b0086779bcee

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: false
  binary_relocation: false  # [osx]

requirements:
  host:
    - ocaml
    - ocaml-findlib
    - ocaml-num
  run:
    - ocaml
    - ocaml-findlib
    - ocaml-num

test:
  source_files:
    - toplevel/g_toplevel.mlg
  commands:
    - coqc -v
    - coqpp toplevel/g_toplevel.mlg

about:
  home: https://coq.inria.fr
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: Coq is a formal proof management system
  doc_url: https://coq.inria.fr/documentation
  dev_url: https://github.com/coq/coq

extra:
  recipe-maintainers:
    - isuruf
    - slel
    - Zimmi48
