travis:
  secure:
    BINSTAR_TOKEN: MI0F2gUMarz3lY1MU0tnWPxI7wsU1OiUIUDgV7iJDx+pCVd9ir67/Y1x6f0P/F8sDnqGKgO/4P90ON3wB/awPAMdf8qOQedC+8PD6S2IzO5+4M7K1e9v/7nlZ+vOVvroMAXbAxBkxrpsQb5cJuzZbf+KxAHP0zoehFHJ1+uxtd+SHRwleVVKvaDMo4iFnDM/lTEOzUs2yIrE6DobByVhH9nYnqXtbzb0gh2NGLVuKxTkve+iNQABN6W63UcUyJbXEUq+fVuQYuhwuXCiAvGCaaklwF7frUKrW72DouPMQeRbBpRoDQHHD3atqArnwVtNwDkzOOf0fE25VFlQ95sGstXZ0d8Bf6RT3aX1O1E8uR3ItGUZsjqaGhRH7ehX0NXqHEvgB85dDB9yvpPeixEv3AL0n7m3PUohLfqSfL4kBkLWwWAZH8rrpPU1qzCSZHqC38WQsRBtS/E7bqqWwyera0cW7VPC12YytrUZwU/8Kxt8eorQTIkbfcezDaRL8ZU83JtFQ1/WBmKG3th4xVCmdKEIt8w554V2jsJA7hFBu0U5s3XYqiC550KB3JbrkwW2GKDvftGVpJbhcxhKAgcSj6zhfQlPkqcGWZQvbUqArVvkHh2gRVF/80+gz5KYMDsbJeN8uOzhcL61zmOxLPVUV3KRQEY3dLCcGV8LgpTq6os=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
